export const userTypes = { SET_CURRENT_USER: "SET_CURRENT_USER" };
export const cartTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
  CLEAR_OUT_ITEM_FROM_CART: "CLEAR_OUT_ITEM_FROM_CART"
};
